// Public Google Maps review excerpts. Names are withheld on this site for privacy.
(() => {
  const sourceUrl = "https://www.google.com/maps/place/My+EDU+Prep/data=!4m6!3m5!1s0x357ca1921d309253:0x3888575f429f0af6!9m1!1b1!16s%2Fg%2F11rpdckq9s";
  const rows = [
    ["Lesson arrangement was simple, and the tutor was extremely professional. Recommended!", "3 years ago"],
    ["I received a comprehensive phone consultation regarding my application for a PhD in the UK. I was truly grateful for the quick and kind response, even though I contacted you on the same day.", "a month ago"],
    ["I met MyEduPrep in early October 2025 and applied to three UK master's programs in education: Edinburgh, UCL, and Cambridge. I was accepted to all three.", "Edited 7 months ago"],
    ["I received help editing my personal statement and CV while applying for a master's degree in business administration after completing my undergraduate degree in the UK.", "7 months ago"],
    ["별점 5점으로 My EDU Prep의 서비스를 평가해주셨습니다.", "3 years ago"],
    ["My child was attending high school in Korea and preparing for UK university admissions, but felt overwhelmed. I discovered this service through an internet search.", "9 months ago"],
    ["I received editing services in the field of economics. I struggled with my CV and SOP on my own, but decided to seek consulting.", "9 months ago"],
    ["During my undergraduate studies in physics, I completed a research internship and began preparing to apply for a Master's program in Mathematical Sciences at Oxford or Cambridge.", "11 months ago"],
    ["I received consulting on my personal statement, resume, and additional documents for my master's degree application in the U.S.", "10 months ago"],
    ["I received editing for my personal statement and CV while applying for a Master's program in the UK in Biology.", "10 months ago"],
    ["As I hold a Master's degree and this is a specialized field, I felt it was crucial to find someone knowledgeable in this area. I trusted the consultant because they also majored in economics.", "10 months ago"],
    ["I wanted to prepare for my master's degree abroad, but I had no information on the subject, so I chose MyEduPrep to seek expert help in Computer Science.", "a year ago"],
    ["I received consulting on my Statement of Purpose and CV for my UK postgraduate application after previously applying through a different agency.", "a year ago"],
    ["Consulting with Marian Tutor was incredibly helpful. While preparing to apply to a US PhD program, I received advice on writing my Statement of Purpose and Personal Statement.", "a year ago"],
    ["I received personal statement editing for my application to the UCL Management Master's program. I'm extremely satisfied with the completed editing, and it's highly professional.", "a year ago"],
    ["I really appreciated the objective review of my documents before editing. I received SOP and CV consulting for my Masters in Public Health application.", "Edited a year ago"],
    ["I received SOP editing consulting for my chemistry department transfer application to an American university.", "2 years ago"],
    ["I received editing for my CV, SoP, and cover letter for my US PhD application. The consultant provided valuable comments on content, format, and writing style.", "a year ago"],
    ["I'm an undergraduate student majoring in chemistry at DGIST and preparing to study abroad.", "2 years ago"],
    ["I was deeply disappointed with the SOP I received from a large study abroad agency. My EDU Prep offered the professional support I had been looking for.", "Edited 4 years ago"],
    ["You provided concrete guidelines and presented my chances of acceptance, which really calmed my anxiety while applying for a Master's degree.", "Edited 4 years ago"],
    ["Through a school program, I received lectures, one-on-one counseling, and three rounds of CV editing to prepare for master's degree admission.", "2 years ago"],
    ["Reviews were the most important factor while I looked for an agency to help with my study abroad preparation. That is how I discovered MyEduPrep.", "2 years ago"],
    ["I received personal statement consulting for my Master's application in the UK. I had no overseas experience and had never written a personal statement before.", "4 years ago"],
    ["I had my motivation letter edited to prepare for admission to a Hungarian veterinary school. They thoroughly reviewed my grammar, expressions, and overall content.", "Edited 4 years ago"],
    ["Here is my review of the consultation and editing service. The process ran from early October to late October 2023.", "Edited 2 years ago"],
    ["While preparing for my PhD application to a US graduate school, I received document editing services from My Edu Prep and received tremendous help.", "3 years ago"],
    ["Five stars. This is a place with truly passionate, thoughtful, and excellent teachers—true educators.", "Edited 4 years ago"],
    ["I took both pronunciation and speaking classes with Teacher Marian while preparing to study abroad.", "2 years ago"],
    ["I received editing services for my motivation letter and CV for my veterinary school application. The result was highly professional.", "Edited 4 years ago"],
    ["I'm a working professional in the UK's NHS and preparing for a master's degree. I requested consultation to prepare for my UK master's application.", "Edited 3 years ago"],
    ["I had my US undergraduate transfer essays edited by MyEduPrep, and I'm truly satisfied.", "4 years ago"],
    ["I found MyEduPrep right before I was about to return to college after taking a two-year leave of absence for military service.", "2 years ago"],
    ["I'm a student preparing to study abroad in the UK. I had received an offer and was stressed about IELTS Speaking, so I joined the group lessons.", "4 years ago"],
    ["After taking Marianne's presentation and speaking classes, I was able to identify my weaknesses and improve and grow from them.", "Edited 4 years ago"],
    ["I was preparing for IELTS on my own while working, but hit a wall with speaking. Teacher Marian's videos were so helpful that I contacted her right away.", "2 years ago"],
    ["While preparing for my UK master's application, I was unsure how to write my personal statement and CV. I found MyEduPrep through an online search.", "Edited 4 years ago"],
    ["While preparing application documents for a UK graduate school, I felt lost regarding how to write and structure my personal statement, so I sought consultation.", "3 years ago"],
    ["I took a pronunciation correction class. I learned helpful intonation tips and the importance of confidence, and received thorough feedback.", "2 years ago"],
    ["I took classes with Ms. Marianne during high school. She meticulously planned lessons to help students gain confidence in English as a means of communication.", "Edited 4 years ago"],
    ["Through a conversion internship arranged by my company, I took IELTS General reading and speaking classes with Ms. Marian for two weeks.", "3 years ago"],
    ["I prepared with Teacher Marianne, studied abroad in the UK, and am about to graduate. She possesses both skill and passion, so I genuinely recommend MyEduPrep.", "Edited 3 years ago"],
    ["I had always heard that discussion in English improves speaking, but did not know where or how to do it. This class was the perfect fit.", "Edited 4 years ago"],
    ["You are the teacher who made me, someone who hated studying, actually study. Igniting a passion for learning mattered even more than improving academic skills.", "Edited 4 years ago"],
    ["I am a student at Warwick University. Language is one of the most crucial factors for studying and living in a foreign country.", "Edited 4 years ago"],
    ["The teacher's English is excellent, and I found the class practical and encouraging. I really wanted to take her class again.", "Edited 4 years ago"],
    ["I had my SOP edited before applying for a PhD in materials science. I chose the service after seeing that the editors were Oxbridge graduates.", "Edited 4 years ago"],
    ["I decided to start studying for IELTS on my own, then received a consultation with Teacher Marianne when I reached a difficult point.", "Edited 4 years ago"],
    ["I am currently a graduate student in a science field and decided to learn English for my academic and professional goals.", "Edited 4 years ago"],
    ["I've participated in the Speaking Project for two months. In terms of value, it is one of the best learning experiences I have found.", "Edited 4 years ago"],
    ["I'm an art major who received help preparing for an interview, including portfolio presentation and follow-up questions. The one-to-one practice was invaluable.", "Edited 4 years ago"],
    ["I am taking the third Academic Writing session because the second session was so informative. This is the first course I have found with this depth.", "Edited 4 years ago"],
    ["My child in IB DP2 needed help with history essay writing. Online classes with Teacher Charlie were very helpful, and the coordination was thoughtful.", "Edited 4 years ago"],
    ["While preparing to become a US nurse, I needed an IELTS overall score of 6.5 and speaking score of 7.0. I finally found a path forward with the speaking support.", "Edited 4 years ago"],
    ["They are completely professional and friendly. You can take care of everything related to studying abroad here.", "Edited 4 years ago"],
    ["It was an urgent document, so I was very anxious, but thank you for editing it so thoroughly.", "2 years ago"],
    ["You shared a lot of useful information, and the feedback you provided was very helpful.", "4 years ago"],
    ["별점 5점으로 My EDU Prep의 서비스를 평가해주셨습니다.", "Edited 4 years ago"],
    ["별점 5점으로 My EDU Prep의 서비스를 평가해주셨습니다.", "Edited 4 years ago"],
    ["I received consulting from MyEduPrep while preparing to apply to UK postgraduate schools, including Cambridge and Imperial College London.", "5 days ago"],
    ["별점 5점으로 My EDU Prep의 서비스를 평가해주셨습니다.", "2 years ago"],
    ["별점 5점으로 My EDU Prep의 서비스를 평가해주셨습니다.", "2 years ago"]
  ];

  // 한국어 페이지에서는 Google 후기의 공개 원문을 자연스러운 한국어로 번역해 표시합니다.
  // 원문 배열은 카테고리 분류와 출처 확인을 위해 그대로 보존합니다.
  const translations = [
    "수업 일정 조율이 간편했고, 선생님도 매우 전문적이었습니다. 추천합니다!",
    "영국 박사과정 지원과 관련해 종합적인 전화 상담을 받았습니다. 당일에 문의드렸는데도 빠르고 친절하게 답변해주셔서 정말 감사했습니다.",
    "2025년 10월 초 My EDU Prep을 만나 에든버러, UCL, 케임브리지의 교육학 석사과정 세 곳에 지원했고, 세 학교 모두 합격했습니다.",
    "영국에서 학부를 마친 뒤 경영학 석사과정에 지원하며 자기소개서와 CV 첨삭 도움을 받았습니다.",
    null,
    "아이가 한국에서 고등학교를 다니며 영국 대학 입시를 준비하고 있었지만 막막함을 느끼고 있었습니다. 인터넷 검색을 통해 My EDU Prep을 알게 되었습니다.",
    "경제학 분야 지원서 첨삭을 받았습니다. 혼자 CV와 SOP를 준비하며 어려움을 겪다가 컨설팅을 신청하게 되었습니다.",
    "물리학 학부 과정에서 연구 인턴십을 마친 뒤 옥스퍼드 또는 케임브리지 수리과학 석사과정 지원을 준비했습니다.",
    "미국 석사과정 지원을 위해 자기소개서, 이력서와 추가 서류에 대한 컨설팅을 받았습니다.",
    "영국 생물학 석사과정에 지원하며 자기소개서와 CV 첨삭을 받았습니다.",
    "이미 석사학위가 있고 전문성이 필요한 분야라 해당 분야를 잘 아는 분을 찾는 것이 중요했습니다. 컨설턴트님도 경제학을 전공하셔서 신뢰할 수 있었습니다.",
    "해외 석사 유학을 준비하고 싶었지만 관련 정보가 전혀 없어, 컴퓨터과학 분야의 전문적인 도움을 받고자 My EDU Prep을 선택했습니다.",
    "다른 유학원을 통해 지원했던 경험 이후, 영국 대학원 지원을 위한 SOP와 CV 컨설팅을 받았습니다.",
    "마리안 선생님의 컨설팅이 큰 도움이 되었습니다. 미국 박사과정을 준비하며 SOP와 Personal Statement 작성에 관한 조언을 받았습니다.",
    "UCL Management 석사과정 지원을 위해 자기소개서 첨삭을 받았습니다. 완성된 결과가 매우 전문적이어서 정말 만족합니다.",
    "첨삭을 시작하기 전 서류를 객관적으로 검토해주신 점이 특히 좋았습니다. 보건학 석사 지원을 위한 SOP와 CV 컨설팅을 받았습니다.",
    "미국 대학 화학과 편입 지원을 위해 SOP 첨삭 컨설팅을 받았습니다.",
    "미국 박사과정 지원을 위해 CV, SOP와 Cover Letter 첨삭을 받았습니다. 내용과 형식, 글쓰기 방식 전반에 걸쳐 유익한 피드백을 받았습니다.",
    "DGIST에서 화학을 전공하며 해외 유학을 준비하고 있는 학부생입니다.",
    "대형 유학원에서 받은 SOP에 크게 실망했는데, My EDU Prep에서 제가 찾던 전문적인 도움을 받을 수 있었습니다.",
    "구체적인 가이드라인과 합격 가능성을 함께 제시해주셔서 석사 지원 과정에서 느끼던 불안이 크게 줄었습니다.",
    "학교 프로그램을 통해 석사 입학 준비를 위한 강의와 일대일 상담, 세 차례의 CV 첨삭을 받았습니다.",
    "유학 준비를 도와줄 곳을 찾을 때 후기를 가장 중요하게 살펴봤고, 그렇게 My EDU Prep을 알게 되었습니다.",
    "영국 석사 지원을 위해 자기소개서 컨설팅을 받았습니다. 해외 경험이 없었고 자기소개서를 작성해본 적도 없어 막막했습니다.",
    "헝가리 수의대 입학 준비를 위해 Motivation Letter 첨삭을 받았습니다. 문법과 표현, 전체적인 내용을 꼼꼼하게 검토해주셨습니다.",
    "2023년 10월 초부터 말까지 진행한 컨설팅과 첨삭 서비스에 대한 후기입니다.",
    "미국 대학원 박사과정 지원을 준비하며 My EDU Prep에서 서류 첨삭을 받았고 큰 도움을 얻었습니다.",
    "별점 5점입니다. 열정과 배려, 뛰어난 실력을 모두 갖춘 진정한 교육자들이 계신 곳입니다.",
    "유학을 준비하면서 마리안 선생님께 발음과 스피킹 수업을 모두 들었습니다.",
    "수의대 지원을 위한 Motivation Letter와 CV 첨삭을 받았으며, 결과물이 매우 전문적이었습니다.",
    "영국 NHS에서 근무하며 석사과정을 준비하고 있습니다. 영국 석사 지원 준비를 위해 컨설팅을 신청했습니다.",
    "미국 학부 편입 에세이를 My EDU Prep에서 첨삭받았고 정말 만족합니다.",
    "군 복무로 2년간 휴학한 뒤 대학에 복학하기 직전에 My EDU Prep을 알게 되었습니다.",
    "영국 유학을 준비하는 학생입니다. 학교 오퍼를 받은 뒤 IELTS Speaking 때문에 고민하다 그룹 수업에 참여했습니다.",
    "마리안 선생님의 프레젠테이션과 스피킹 수업을 통해 제 약점을 정확히 파악하고 보완하며 성장할 수 있었습니다.",
    "직장생활과 함께 IELTS를 독학하다 스피킹에서 한계를 느꼈습니다. 마리안 선생님의 영상이 큰 도움이 되어 바로 연락드렸습니다.",
    "영국 석사 지원을 준비하며 자기소개서와 CV를 어떻게 써야 할지 막막했습니다. 온라인 검색을 통해 My EDU Prep을 찾았습니다.",
    "영국 대학원 지원 서류를 준비하면서 자기소개서의 구성과 작성 방법이 막막해 컨설팅을 신청했습니다.",
    "발음 교정 수업을 들었습니다. 유용한 억양 팁과 자신감의 중요성을 배웠고, 꼼꼼한 피드백도 받을 수 있었습니다.",
    "고등학교 때 마리안 선생님의 수업을 들었습니다. 학생들이 영어를 소통의 도구로 자신 있게 사용할 수 있도록 수업을 세심하게 설계해주셨습니다.",
    "회사에서 마련한 전환형 인턴십을 통해 2주 동안 마리안 선생님의 IELTS General Reading과 Speaking 수업을 들었습니다.",
    "마리안 선생님과 준비해 영국에서 유학했고 이제 졸업을 앞두고 있습니다. 실력과 열정을 모두 갖춘 분이라 My EDU Prep을 진심으로 추천합니다.",
    "영어 토론이 스피킹 향상에 도움이 된다는 이야기는 많이 들었지만 어디서 어떻게 해야 할지 몰랐습니다. 이 수업이 저에게 꼭 맞았습니다.",
    "공부를 싫어하던 제가 스스로 공부하게 만들어주신 선생님입니다. 학업 능력의 향상보다 배움에 대한 열정을 일깨워주신 점이 더욱 소중했습니다.",
    "Warwick University에 재학 중입니다. 외국에서 공부하고 생활할 때 언어는 가장 중요한 요소 중 하나입니다.",
    "선생님의 영어 실력이 뛰어나고 수업은 실용적이면서도 용기를 북돋아주었습니다. 꼭 다시 수업을 듣고 싶었습니다.",
    "재료과학 박사과정 지원을 앞두고 SOP 첨삭을 받았습니다. Oxbridge 출신 전문가들이 첨삭한다는 점을 보고 선택했습니다.",
    "IELTS를 독학으로 시작했다가 어려움을 느끼는 시점에 마리안 선생님과 상담을 진행했습니다.",
    "현재 이공계 대학원생으로, 학업과 진로 목표를 위해 영어를 배우기로 결심했습니다.",
    "Speaking Project에 두 달 동안 참여했습니다. 비용 대비 가치 면에서 제가 경험한 최고의 학습 중 하나였습니다.",
    "미술 전공 지원자로서 포트폴리오 설명과 후속 질문을 포함한 인터뷰 준비 도움을 받았습니다. 일대일 연습이 정말 큰 도움이 되었습니다.",
    "두 번째 Academic Writing 과정이 매우 유익해 세 번째 과정까지 수강하고 있습니다. 이처럼 깊이 있는 수업은 처음입니다.",
    "IB DP2 과정 중인 아이가 역사 에세이 작성에 도움이 필요했습니다. Charlie 선생님의 온라인 수업이 매우 유익했고 수업 조율도 세심했습니다.",
    "미국 간호사 준비를 위해 IELTS Overall 6.5와 Speaking 7.0이 필요했습니다. 스피킹 수업을 통해 마침내 준비 방향을 찾을 수 있었습니다.",
    "매우 전문적이면서도 친절합니다. 유학과 관련된 모든 준비를 이곳에서 도움받을 수 있습니다.",
    "급하게 준비해야 하는 서류라 많이 불안했는데, 끝까지 꼼꼼하게 첨삭해주셔서 감사합니다.",
    "유용한 정보를 많이 알려주셨고, 제공해주신 피드백도 큰 도움이 되었습니다.",
    null,
    null,
    "케임브리지와 Imperial College London을 포함한 영국 대학원 지원을 준비하며 My EDU Prep에서 컨설팅을 받았습니다.",
    null,
    null
  ];

  const categoryFor = (text) => {
    const value = text.toLowerCase();
    if (/interview|면접/.test(value)) return "인터뷰";
    if (/ielts|speaking|pronunciation|영어/.test(value)) return "Academic English";
    if (/parent|child|학부모|자녀/.test(value)) return "학부모 컨설팅";
    if (/edit|essay|personal statement|sop|cv|document/.test(value)) return "첨삭";
    return "대학 · 대학원";
  };

  window.MEP_GOOGLE_REVIEWS_KO = rows.map(([originalText, date], index) => {
    const text = translations[index] || originalText;
    return {
    id: `google-${index + 1}`,
    title: text.length > 68 ? `${text.slice(0, 65).trim()}…` : text,
    text,
    displayName: "Google 이용자",
    institution: "Google 후기",
    category: categoryFor(originalText),
    source: "Google",
    rating: 5,
    date,
    featured: false,
    anonymous: true,
    url: sourceUrl
    };
  });
})();
